#!/usr/bin/env python3
"""Exact rank certificates for fixed coordinate sections of an embedded E8.

The complete projection domain is regenerated by verify.py. No Weyl action
on the ambient lattice is assumed. Integer minors prove uniqueness of the
fixed-stabilizer orbit masses; rational moments identify their values.
"""
import argparse
from collections import Counter, defaultdict
from fractions import Fraction
from functools import lru_cache
import hashlib
import importlib.util
from itertools import permutations
import json
from math import comb, isqrt, prod
from pathlib import Path


HERE = Path(__file__).resolve().parent
SPEC = importlib.util.spec_from_file_location("e8_projection_domain", HERE / "verify.py")
DOMAIN = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(DOMAIN)
PRIME = 1000003
AVERAGES = {0: Fraction(1092000), 2: Fraction(116235), 4: Fraction(9180),
            6: Fraction(495), 8: Fraction(63, 4)}
# Zero-based row indices, in basis_labels(k) order. Columns are ordered by
# the lexicographically least doubled-coordinate representative of each orbit.
RANK_CERTIFICATES = {
    1: ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20,
         21, 22, 26, 29, 31], 910777),
    2: ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20,
         21, 22, 23, 24, 25, 26, 27, 28, 32, 34, 37, 39, 42, 44], 790744),
    3: ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
         21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32, 34, 37, 40, 42, 43, 45, 47, 52], 894205),
    4: ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
         21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32, 34, 36, 38, 41, 43, 45, 47, 51, 52, 54], 314211),
    5: ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
         21, 22, 23, 24, 25, 26, 27, 28, 30, 31, 33, 35, 37, 40, 43, 45, 48, 49, 51], 401115),
    6: ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20,
         21, 22, 23, 24, 25, 27, 28, 30, 32, 34, 38, 42, 47, 48], 244188),
    7: ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 20,
         22, 24, 26, 29, 32], 296071),
    8: ([0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 15], 272057),
}
# Applying these reflections in this order to Q(alpha_i) gives alpha_i.
# The numbering here is zero-based; reports also give the paper's 1-based word.
WEYL_WORD = (0, 2, 0, 3, 1, 2, 0, 4, 3, 1, 2, 0, 3, 2, 5, 4, 3, 1, 2, 0,
             3, 2, 4, 3, 1, 5, 4, 3, 2, 0, 7)


def require(condition, message):
    if not condition:
        raise ValueError(message)


@lru_cache(None)
def partitions(total, length, maximum=5):
    if total == 0:
        return ((),)
    if length == 0:
        return ()
    return tuple((a,) + tail for a in range(min(total, maximum), 0, -1)
                 for tail in partitions(total-a, length-1, a))


@lru_cache(None)
def monomial_exponents(partition, length):
    """Distinct monomials in a monomial symmetric polynomial, coefficient one."""
    return tuple(sorted(set(permutations(partition + (0,)*(length-len(partition))))))


def basis_labels(k):
    require(isinstance(k, int) and 1 <= k <= 8, "Coordinate section rank")
    return tuple((left, right) for degree in range(6) for a in range(degree+1)
                 for left in partitions(a, k) for right in partitions(degree-a, 8-k))


def symmetric_polynomial(squares, partition):
    return sum(prod(x**a for x, a in zip(squares, alpha))
               for alpha in monomial_exponents(partition, len(squares)))


def evaluate(u, k, label):
    left, right = label
    return (symmetric_polynomial(tuple(x*x for x in u[:k]), left)
            * symmetric_polynomial(tuple(x*x for x in u[k:]), right))


def moment(k, label):
    # u=2 lambda=2 sqrt(3) times the physical section projection. Coordinate
    # functionals have Gram 12 I, hence the sphere moment has factor 6*12=72.
    left, right = label
    degree = sum(left) + sum(right)
    require(0 <= degree <= 5, "Moment exceeds the 11-design degree")
    coefficient = len(monomial_exponents(left, k))*len(monomial_exponents(right, 8-k))
    return Fraction(52416000 * 72**degree * coefficient
                    * prod(prod(range(1, 2*a, 2)) for a in left+right),
                    prod(48+2*j for j in range(degree)))


def orbit_groups(domain, k):
    groups = defaultdict(list)
    for u in sorted(domain):
        key = (tuple(sorted(x*x for x in u[:k])),
               tuple(sorted(x*x for x in u[k:])), prod(u))
        groups[key].append(u)
    return tuple(tuple(group) for group in sorted(groups.values(), key=lambda group: group[0]))


def determinant_mod(matrix, modulus=PRIME):
    n = len(matrix)
    require(n > 0 and all(len(row) == n for row in matrix), "Square rank minor required")
    require(all(isinstance(x, int) for row in matrix for x in row), "Integer rank minor required")
    a = [[x % modulus for x in row] for row in matrix]
    determinant = 1
    for column in range(n):
        pivot = next((i for i in range(column, n) if a[i][column]), None)
        if pivot is None:
            return 0
        if pivot != column:
            a[column], a[pivot] = a[pivot], a[column]
            determinant = -determinant
        value = a[column][column]
        determinant = determinant*value % modulus
        inverse = pow(value, -1, modulus)
        for i in range(column+1, n):
            factor = a[i][column]*inverse % modulus
            for j in range(column+1, n):
                a[i][j] = (a[i][j]-factor*a[column][j]) % modulus
            a[i][column] = 0
    return determinant % modulus


def check_rank(matrix, rows, expected):
    n = len(matrix[0])
    require(len(rows) == len(set(rows)) == n and all(0 <= i < len(matrix) for i in rows),
            "Rank row selection")
    determinant = determinant_mod([matrix[i] for i in rows])
    require(determinant == expected and determinant != 0, "Rank minor certificate")
    return determinant


def coordinate_count(m):
    require(isinstance(m, int) and 0 <= m <= 7, "Complement dimension")
    return (1092000 + 18360*m + 464944*comb(m, 2) + 11880*comb(m, 3)
            + 146880*comb(m, 4) + 2520*comb(m, 5) + 31680*comb(m, 6))


def system(domain, roots, k):
    groups, labels = orbit_groups(domain, k), basis_labels(k)
    matrix = [[evaluate(group[0], k, label) for group in groups] for label in labels]
    rhs = [moment(k, label)-sum(evaluate(u, k, label) for u in roots) for label in labels]
    masses = [len(group)*AVERAGES[sum(x*x for x in group[0])//4] for group in groups]
    return groups, labels, matrix, rhs, masses


def check_moments(matrix, rhs, masses):
    require(len(matrix) == len(rhs) and all(len(row) == len(masses) for row in matrix),
            "Moment system dimensions")
    require(all(sum(a*x for a, x in zip(row, masses)) == b for row, b in zip(matrix, rhs)),
            "Candidate orbit masses fail an exact moment")


def coordinate_weyl_map(u):
    # Q=P_(5,8) diag(J_4-2I_4,J_4-2I_4)/2.
    numerator = [sum(u[start:start+4])-2*u[i]
                 for start in (0, 4) for i in range(start, start+4)]
    require(all(x % 2 == 0 for x in numerator), "Weyl-map coordinate integrality")
    result = [x//2 for x in numerator]
    result[4], result[7] = result[7], result[4]
    return tuple(result)


def check_weyl_map(word=WEYL_WORD):
    roots, simple = DOMAIN.root_set(), DOMAIN.simple_roots()
    require({coordinate_weyl_map(r) for r in roots} == roots, "Weyl map root set")
    images = [coordinate_weyl_map(r) for r in simple]
    original_images = list(images)
    for i in word:
        images = [DOMAIN.reflect(r, simple[i]) for r in images]
    require(images == simple, "Weyl reflection word")
    require(all(not any(r[5:]) for r in original_images[:5]), "Mapped D5 coordinate support")
    require(determinant_mod([list(r[:5]) for r in original_images[:5]]) != 0,
            "Mapped D5 dimension")
    return {"simple_reflection_word_1_based": [i+1 for i in word],
            "mapped_first_five_doubled_roots": original_images[:5]}


def check():
    require(all(PRIME % d for d in range(2, isqrt(PRIME)+1)), "Rank modulus is not prime")
    domain = DOMAIN.admissible_domain()
    roots = {tuple(3*x for x in r) for r in DOMAIN.root_set()}
    require(Counter(sum(x*x for x in u)//4 for u in domain)
            == {0: 1, 2: 240, 4: 2160, 6: 6720, 8: 17280}, "Complete domain shell sizes")
    require(len(roots) == 240 and not (domain & roots), "Exceptional root separation")
    families = {}
    for k in range(1, 9):
        groups, labels, matrix, rhs, masses = system(domain, roots, k)
        rows, expected = RANK_CERTIFICATES[k]
        residue = check_rank(matrix, rows, expected)
        check_moments(matrix, rhs, masses)
        target = [not any(group[0][:k]) for group in groups]
        require(all(all((not any(u[:k])) == t for u in group)
                    for group, t in zip(groups, target)), "Target not invariant on an orbit")
        profile = Counter(sum(x*x for x in u)//4 for u in domain if not any(u[:k]))
        m = 8-k
        predicted = {0: 1, 2: 4*comb(m, 2), 4: 2*m+16*comb(m, 4),
                     6: 24*comb(m, 3)+64*comb(m, 6), 8: 160*comb(m, 5)}
        require(dict(profile) == {n: count for n, count in predicted.items() if count},
                "Coordinate complement shell profile")
        exceptional = sum(not any(u[:k]) for u in roots)
        require(exceptional == 4*comb(m, 2), "Coordinate complement exceptional roots")
        count = sum(mass for mass, t in zip(masses, target) if t)+exceptional
        require(count == coordinate_count(m), "Coordinate count formula")
        families[k] = {
            "subsystem": "coordinate axis" if k == 1 else f"D{k}",
            "moment_matrix_shape": [len(matrix), len(groups)],
            "full_column_rank": len(groups), "rank_rows_zero_based": rows,
            "rank_prime": PRIME, "rank_minor_determinant_mod_prime": residue,
            "ordered_moment_labels": [[list(a), list(b)] for a, b in labels],
            "ordered_orbits": [{"representative": group[0], "size": len(group),
                                "lambda_squared_norm": sum(x*x for x in group[0])//4,
                                "forced_total_multiplicity": str(mass)}
                               for group, mass in zip(groups, masses)],
            "target_nonexceptional_shell_profile": dict(sorted(profile.items())),
            "target_exceptional_roots": exceptional,
            "fixed_coordinate_section_count": int(count),
        }
    return {"passed": True, "cut_count": 8, "nonexceptional_domain_size": len(domain),
            "exceptional_domain_size": len(roots), "maximum_moment_degree": 10,
            "rank_certificate_arithmetic": "integer elimination modulo prime 1000003",
            "moment_arithmetic": "exact rational", "families": families,
            "specified_D5_weyl_correspondence": check_weyl_map(),
            "domain_verifier_sha256": hashlib.sha256((HERE / "verify.py").read_bytes()).hexdigest(),
            "premises": ["Extremal even unimodular rank-48 lattice with an embedded sqrt(3) E8",
                         "Minimal shell has 52416000 vectors and is a spherical 11-design"],
            "ambient_automorphisms_assumed": False}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    report = json.dumps(check(), indent=2) + "\n"
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report)
    print(report, end="")
